[theme]
primaryColor = "#0285FF"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#020817"
font = "Inter"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[deprecation]
showfileUploaderEncoding = false

[global]
developmentMode = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[runner]
fastReruns = true

[logger]
level = "info" 