[theme]
primaryColor = "#0285FF"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#FFFFFF"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[deprecation]
showfileUploaderEncoding = false

[global]
developmentMode = false
showWarningOnDirectExecution = true

[client]
toolbarMode = "minimal"
showErrorDetails = false

[runner]
fastReruns = true

[logger]
level = "info" 